apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcube-viewer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcube-viewer
  template:
    metadata:
      labels:
        app: xcube-viewer
        track: stable
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
      containers:
        - name: xcube-viewer
          image: {{ .Values.viewerImage }}
          ports:
            - name: http
              containerPort: 80

          #imagePullPolicy: Always
          #   - name: health
          #     containerPort: 81
          # resources:
          #   limits:
          #     cpu: 0.2
          #     memory: "10Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 81
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 15
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 81
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
